#!/usr/bin/env bash
#
# Claudia backend deploy helper (self-hosted VPS + Docker Compose).
#
# Deploys the prod topology from infra/docker-compose.prod.yml: the FastAPI gateway behind
# Caddy (automatic Let's Encrypt TLS). Secrets never live in the repo — they come from an env
# file OUTSIDE it (CLAUDIA_ENV_FILE, default /etc/claudia/claudia.env). See docs/DEPLOYMENT.md.
#
# Usage (run on the VPS, from anywhere):
#   CLAUDIA_DOMAIN=claudia.gogix.dev scripts/deploy.sh init     # scaffold the secrets file once
#   CLAUDIA_DOMAIN=claudia.gogix.dev scripts/deploy.sh deploy   # build + (re)start + health check
#   scripts/deploy.sh status | logs | down
#
# Config (environment variables, all optional except where noted):
#   CLAUDIA_DOMAIN     public hostname Caddy provisions TLS for   (REQUIRED for init/deploy)
#   CLAUDIA_ENV_FILE   path to the secrets env file OUTSIDE repo  (default /etc/claudia/claudia.env)
#   GIT_PULL=1         `git pull --ff-only` before deploying      (default off)
#   HEALTH_TIMEOUT     seconds to wait for the gateway to be healthy (default 90)
set -euo pipefail

# --- resolve paths & config ------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$REPO_ROOT/infra/docker-compose.prod.yml"
CLAUDIA_ENV_FILE="${CLAUDIA_ENV_FILE:-/etc/claudia/claudia.env}"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-90}"
CMD="${1:-deploy}"

# --- pretty output ---------------------------------------------------------
c_red=$'\033[31m'; c_grn=$'\033[32m'; c_yel=$'\033[33m'; c_dim=$'\033[2m'; c_off=$'\033[0m'
info() { printf '%s==>%s %s\n' "$c_grn" "$c_off" "$*"; }
warn() { printf '%s[warn]%s %s\n' "$c_yel" "$c_off" "$*" >&2; }
die()  { printf '%s[error]%s %s\n' "$c_red" "$c_off" "$*" >&2; exit 1; }

# --- docker compose command (v2 plugin preferred, v1 fallback) -------------
compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose -f "$COMPOSE_FILE" "$@"
  elif command -v docker-compose >/dev/null 2>&1; then
    docker-compose -f "$COMPOSE_FILE" "$@"
  else
    die "Docker Compose not found. Install Docker Engine + the compose plugin."
  fi
}

require_domain() {
  [ -n "${CLAUDIA_DOMAIN:-}" ] || die "CLAUDIA_DOMAIN is not set (e.g. CLAUDIA_DOMAIN=claudia.gogix.dev)."
}

preflight() {
  command -v docker >/dev/null 2>&1 || die "docker not found on PATH."
  docker info >/dev/null 2>&1 || die "cannot talk to the Docker daemon (is it running? are you in the 'docker' group?)."
  [ -f "$COMPOSE_FILE" ] || die "compose file missing: $COMPOSE_FILE"
}

# --- scaffold the secrets file (init) --------------------------------------
gen_vault_key() {
  # A Fernet key = url-safe base64 of 32 random bytes. Prefer the real generator; fall back
  # to openssl so `init` works even before Python deps are installed on the host.
  if python3 -c "from cryptography.fernet import Fernet" >/dev/null 2>&1; then
    python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
  elif command -v openssl >/dev/null 2>&1; then
    openssl rand 32 | base64 | tr '+/' '-_'
  else
    die "need python3+cryptography or openssl to generate VAULT_KEY."
  fi
}

cmd_init() {
  require_domain
  if [ -f "$CLAUDIA_ENV_FILE" ]; then
    warn "secrets file already exists: $CLAUDIA_ENV_FILE (leaving it untouched)."
    return 0
  fi
  info "creating secrets file $CLAUDIA_ENV_FILE (chmod 600)"
  local dir; dir="$(dirname "$CLAUDIA_ENV_FILE")"
  mkdir -p "$dir" 2>/dev/null || die "cannot create $dir — re-run with sudo, or set CLAUDIA_ENV_FILE to a writable path."
  local vault; vault="$(gen_vault_key)"
  umask 177
  cat > "$CLAUDIA_ENV_FILE" <<EOF
# Claudia production secrets — DO NOT COMMIT. Managed on the host only (chmod 600).
# Generated by scripts/deploy.sh init on $(date -u +%Y-%m-%dT%H:%M:%SZ).
CLAUDIA_ENV=prod

# Account Vault Fernet key (required in prod). Rotating it re-encrypts stored credentials.
VAULT_KEY=$vault

# Voice backends: stub | whisper / piper. Stubs need no models; switch on once weights exist.
STT_BACKEND=stub
TTS_BACKEND=stub

# Optional live fixtures (falls back to the offline stub when blank).
API_FOOTBALL_KEY=
FOOTBALL_SEASON=2026

# Optional anonymized analytics (in-memory /dev/stats sink when blank).
POSTHOG_API_KEY=
POSTHOG_HOST=https://us.i.posthog.com
EOF
  chmod 600 "$CLAUDIA_ENV_FILE"
  info "done. Edit $CLAUDIA_ENV_FILE to add optional keys, then: CLAUDIA_DOMAIN=$CLAUDIA_DOMAIN scripts/deploy.sh deploy"
}

# --- health check ----------------------------------------------------------
wait_healthy() {
  info "waiting for the gateway to answer /health (up to ${HEALTH_TIMEOUT}s)…"
  local deadline=$((SECONDS + HEALTH_TIMEOUT))
  while [ "$SECONDS" -lt "$deadline" ]; do
    # Check the gateway directly on the internal network (python is in the image; curl isn't).
    if compose exec -T gateway python -c \
      "import sys,urllib.request; sys.exit(0 if urllib.request.urlopen('http://localhost:8000/health',timeout=3).status==200 else 1)" \
      >/dev/null 2>&1; then
      info "${c_grn}gateway healthy${c_off}"
      return 0
    fi
    sleep 3
  done
  warn "gateway did not report healthy within ${HEALTH_TIMEOUT}s — check: scripts/deploy.sh logs"
  return 1
}

check_public_tls() {
  # Best-effort external check. A fresh domain may still be issuing its cert / propagating DNS.
  [ -n "${CLAUDIA_DOMAIN:-}" ] || return 0
  command -v curl >/dev/null 2>&1 || return 0
  info "probing https://$CLAUDIA_DOMAIN/health …"
  if curl -fsS --max-time 10 "https://$CLAUDIA_DOMAIN/health" >/dev/null 2>&1; then
    info "${c_grn}public endpoint live: https://$CLAUDIA_DOMAIN/health${c_off}"
  else
    warn "https://$CLAUDIA_DOMAIN/health not reachable yet — normal on first deploy while Caddy"
    warn "issues the TLS cert / DNS propagates. Confirm the A record points here, then recheck:"
    warn "  scripts/deploy.sh status"
  fi
}

# --- deploy ----------------------------------------------------------------
cmd_deploy() {
  require_domain
  preflight
  [ -f "$CLAUDIA_ENV_FILE" ] || die "secrets file not found: $CLAUDIA_ENV_FILE — run: scripts/deploy.sh init"

  if [ "${GIT_PULL:-0}" = "1" ]; then
    info "git pull --ff-only"
    git -C "$REPO_ROOT" pull --ff-only || die "git pull failed (uncommitted changes or diverged history?)."
  fi

  export CLAUDIA_ENV_FILE CLAUDIA_DOMAIN
  info "building and starting (compose: $COMPOSE_FILE)"
  info "  domain=$CLAUDIA_DOMAIN  env_file=$CLAUDIA_ENV_FILE  ${c_dim}rev=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo n/a)${c_off}"
  compose up -d --build

  wait_healthy || true
  check_public_tls
  echo
  compose ps
}

cmd_status() {
  preflight
  compose ps || true
  check_public_tls
}

cmd_logs() { preflight; compose logs -f --tail=120 "${2:-}"; }

cmd_down() { preflight; info "stopping stack"; compose down; }

case "$CMD" in
  init)   cmd_init ;;
  deploy) cmd_deploy ;;
  status) cmd_status ;;
  logs)   cmd_logs "$@" ;;
  down)   cmd_down ;;
  -h|--help|help) sed -n '2,25p' "$0" ;;
  *) die "unknown command '$CMD' (use: init | deploy | status | logs | down)" ;;
esac
